# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'loanPlatform' do

pod 'FMDB', '~> 2.4'

pod 'SDWebImage', '~> 3.7.1'

pod 'AFNetworking', '~> 2.5.0'

pod 'SVPullToRefresh'

pod 'NullSafe', '~> 1.2.1'

pod 'SVProgressHUD', '~> 1.1.3'

pod 'RDVTabBarController'

pod 'iCarousel', '~> 1.8.1'

end

